#!/bin/bash
###
#
# Check Nova Service
# Author: HoangDH - daohuyhoang87@gmail.com
# Release: 29/8/2017 - 5:30PM
#
###

check_on_other_node() {
source /root/keystonerc_admin
openstack compute service list | grep -w 'nova-compute' > /tmp/info_nova.h2
services=`cat /tmp/info_nova.h2 | grep -w "down" | awk  '{ print $3 }' FS="|" | sort -u`

for service in $services
	do
		node=`cat /tmp/info_nova.h2 | grep -w "down" | grep -w "$service" | awk  '{ print $4 }' FS="|" | sort -u`
		echo -e "$node" >> /tmp/err_nova.h2
	done

}

i=0
f=$(systemctl status openstack-nova-api | grep 'active (running)')
if [ -z "$f" ]
	then
		i=0
	else
		check_on_other_node
		if [ -e /tmp/err_nova.h2 ]
		then
			i=$(cat /tmp/err_nova.h2 | wc -l)
		else 
			i=99999
		fi
fi

rm -rf /tmp/info_nova.h2

case $i in
	99999)
		echo "Nova-compute is running on all compute."
		exit 0
		;;
	[1-99999]*)
		s=`cat /tmp/err_nova.h2` 
		rm -rf /tmp/err_nova.h2
		echo -e "Nova Compute is not running on:"$s
		exit 1
		;;	
	0) 
		echo "Nova-api is not running."
		exit 2
		;;
	*)
		echo "Nova is/are not running."
		exit 3
		;;	
esac

	