#!/bin/bash
###
#
# Check Cinder Services
# Author: HoangDH - daohuyhoang87@gmail.com
# Release: 29/8/2017 - 4:51PM
#
###
i=0

check_on_other_node() {
source /root/keystonerc_admin
openstack volume service list > /tmp/info_cinder.h2
services=`cat /tmp/info_cinder.h2 | grep -w "down" | awk  '{ print $2 }' FS="|" | sort -u`

for service in $services
	do
		node=`cat /tmp/info_cinder.h2 | grep -w "down" | grep -w "$service" | awk  '{ print $3 }' FS="|" | sort -u`
		echo -e "$service: "$node >> /tmp/err_cinder.h2
	done
}

i=0
f=$(systemctl status openstack-cinder-api | grep 'active (running)')
if [ -z "$f" ]
	then
		i=0
	else
		check_on_other_node
		if [ -e /tmp/err_cinder.h2 ]
		then
			i=$(cat /tmp/err_cinder.h2 | wc -l)
		else 
			i=99999
		fi
fi

rm -rf /tmp/info_cinder.h2

case $i in
	99999)
		echo "Cinder-api is running."
		exit 0
		;;
	[1-99998]*)
		s=`cat /tmp/err_cinder.h2` 
		rm -rf /tmp/err_cinder.h2
		echo -e "Cinder is not running.\n$s"
		exit 1
		;;	
	0) 
		echo "Cinder-api is not running."
		exit 2
		;;
	*)
		echo "Cinder is/are not running."
		exit 3
		;;	
esac